- name: Install PyMySQL
  pip:
    name: pymysql
    state: present
    
- name: create database
  community.mysql.mysql_db:
    login_host: "terraform-2023071908424018970000001.cg5yskihsrzx.us-east-1.rds.amazonaws.com" 
    login_user: "teague"
    login_password: "devopspblproject"
    name: wordpressdb
    collation: utf8_general_ci
    encoding: utf8
    state: present


- name: Input wordpress credentials
  ansible.builtin.replace:
    path: /var/www/html/wp-config.php 
    regexp: "{{ item.regexp }}"
    replace: "{{ item.replace }}"
  loop:
    - { regexp: '^localhost', replace: "terraform-2023071908424018970000001.cg5yskihsrzx.us-east-1.rds.amazonaws.com" }
    - { regexp: '^teague', replace: "teague" }
    - { regexp: '^wordpressdb', replace: "wordpressdb" }
    - { regexp: '^devopspblproject', replace: "devopspblproject" }
