- name: Install PyMySQL
  pip:
    name: pymysql
    state: present
    
- name: create database
  community.mysql.mysql_db:
    login_host: "terraform-20231026223857762400000010.chhu3obm1iwk.us-east-1.rds.amazonaws.com"
    login_user: "lego"
    login_password: "1godwynE"
    name: toolingdb
    collation: utf8_general_ci
    encoding: utf8
    state: present

- name: Input tooling credentials
  ansible.builtin.replace:
    path: /var/www/html/functions.php
    regexp: "{{ item.regexp }}"
    replace: "{{ item.replace }}"
  loop:
    - { regexp: '^mysql.tooling.svc.cluster.local', replace: "terraform-20231026223857762400000010.chhu3obm1iwk.us-east-1.rds.amazonaws.com" }
    - { regexp: '^admin', replace: "lego" }
    - { regexp: '^tooling', replace: "toolingdb" }
    - { regexp: '^admin', replace: "1godwynE" }


